# Generated by Django 2.2 on 2022-02-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_auto_20220227_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='admin_comment',
            field=models.CharField(default='', max_length=200, verbose_name='комент_админа'),
        ),
        migrations.AddField(
            model_name='news',
            name='age_rate',
            field=models.CharField(default='', max_length=5, verbose_name='возрастной_ценз '),
        ),
    ]
