# Generated by Django 2.2 on 2022-03-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0008_auto_20220312_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='images_folder',
            field=models.CharField(default='', max_length=1000, verbose_name='папка картинок'),
        ),
    ]
