# Generated by Django 2.2 on 2022-03-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0009_news_images_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='images_folder',
        ),
    ]
