# Generated by Django 2.2 on 2022-03-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0010_remove_news_images_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
