# Generated by Django 2.2 on 2022-03-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0011_news_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
            ],
        ),
    ]
