# Generated by Django 2.2 on 2022-03-15 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0012_uploadnews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadNews',
        ),
    ]
