# Generated by Django 2.2 on 2022-03-16 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0013_delete_uploadnews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='images',
            new_name='image',
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='media/')),
                ('news', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_news.News')),
            ],
        ),
    ]
