# Generated by Django 2.2 on 2022-03-16 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0014_auto_20220316_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
