# Generated by Django 2.2 on 2022-03-21 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0015_remove_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='admin_comment',
            field=models.CharField(default='', max_length=200, verbose_name='admin_comment'),
        ),
        migrations.AlterField(
            model_name='news',
            name='age_rate',
            field=models.CharField(default='', max_length=5, verbose_name='age_rate'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(default='', max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('d', 'Черновик'), ('a', 'Архив'), ('p', 'Опубликовано')], default='d', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.CharField(default='', max_length=50, verbose_name='tag'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='', max_length=50, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=50, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=30, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=50, verbose_name='username'),
        ),
    ]
