# Generated by Django 4.0.3 on 2022-04-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0019_alter_comment_id_alter_news_id_alter_newsimage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
    ]
